config/routes.rb
Tidbit::Application.routes.draw do

  get "/" => 'static_pages#home'
  get "/home" => 'static_pages#home'
  get "/signup" => 'users#new'
  get '/questions/:id/answers/new' => 'answers#new', :as => :new_answer
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  resources :questions, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  resources :answers, only: [:new, :create, :index, :edit, :update, :destroy]
  resources :categories, only: [:new, :create, :index, :show, :edit, :update, :destroy]

  resources :users, only: [:index]
  resources :sessions, only: [:new, :create, :destroy]

  root 'static_pages#home'

end

app/models/question.rb
class Question < ActiveRecord::Base
  validates :user, presence: true
  has_many :answers
  belongs_to :user
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.paginate(:page => params[:page], :per_page => 10)
    @question = Question.new
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)
      @question.user_id = current_user
    puts @question.inspect
    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render action: 'show', status: :created, location: @question }
      else
        format.html { render action: 'new' }
        puts @question.errors[:user] = "must be logged in to post!"
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:title, :content, :user_id)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for @question, html: {class: "pure-form pure-form-stacked"} do |f| %>
    <fieldset>

      <% if @question.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

            <ul>
              <% @question.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div class="pure-control-group">
        <%= f.label :title %>
        <%= f.text_field :title %>
      </div>

      <div class="pure-control-group">
        <%= f.label :content %>
        <%= f.text_area :content %>
      </div>

      <div class="pure-control-group">
        <div class="pure-controls">
          <%= f.submit class: "pure-button pure-button-primary" %>
        </div>
      </div>

    </fieldset>
<% end %>

app/views/questions/_question.html.erb
<div class="question">

  <div class="headline">
    <%= question.title %>
  </div>
  <div class="text">
    <%= question.content %>
  </div>
  
  <div class="meta">
    <span><%= link_to 'Show', question %></span> &middot;
    <span><%= link_to 'Edit', edit_question_path(question) %></span> &middot;
    <span><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></span>
  </div>

  <div class="bio_unit">
    <div class="gravatar"><%= gravatar_for(question.user) %></div>
    <div class="name"><%= question.user.name %></div>
    <div class="bio"><%= question.user.bio %></div>
  </div>
</div>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<% provide(:title, 'Questions') %>

<div class="content">
  <h1>Latest Questions</h1>

  <%= link_to 'Add a Question', '#', class: "pure-button pure-button-primary top-action-button" %>

  <%= render 'questions/form' %>

  <% @questions.each do |question| %>
    <%= render question %>
  <% end %>

  <%= will_paginate %>
</div>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @question.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @question.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @question.user_id %>
</p>

<p>
  <strong>Answers:</strong>
  <br>
  <% @question.answers.each do |answer| %>
    <tr>
      <td>Title: </td>
      <td><%= answer.title %></td>
    </tr>
     <tr>
        <td>Content: </td>
        <td><%= answer.content %></td>
     </tr>
      <br>
  <%end%>
</p>

<%= link_to 'Answer', new_answer_path(@question) %> |
<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>