config/routes.rb
Tidbit::Application.routes.draw do

  get "/" => 'static_pages#home'
  get "/home" => 'static_pages#home'
  get "/signup" => 'users#new'
  get '/questions/:id/answers/new' => 'answers#new', :as => :new_answer
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  resources :questions, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  resources :answers, only: [:new, :create, :index, :edit, :update, :destroy]
  resources :categories, only: [:new, :create, :index, :show, :edit, :update, :destroy]

  resources :users, only: [:index]
  resources :sessions, only: [:new, :create, :destroy]

  root 'static_pages#home'

end

app/models/question_category.rb
class QuestionCategory < ActiveRecord::Base
  belongs_to :question
  belongs_to :category
end

app/controllers/question_categories_controller.rb
class QuestionCategoriesController < ApplicationController
  before_action :set_question_category, only: [:show, :edit, :update, :destroy]

  # GET /question_categories
  # GET /question_categories.json
  def index
    @question_categories = QuestionCategory.paginate(:page => params[:page], :per_page => 10)
  end

  # GET /question_categories/1
  # GET /question_categories/1.json
  def show
  end

  # GET /question_categories/new
  def new
    @question_category = QuestionCategory.new
  end

  # GET /question_categories/1/edit
  def edit
  end

  # POST /question_categories
  # POST /question_categories.json
  def create
    @question_category = QuestionCategory.new(question_category_params)

    respond_to do |format|
      if @question_category.save
        format.html { redirect_to @question_category, notice: 'Question category was successfully created.' }
        format.json { render action: 'show', status: :created, location: @question_category }
      else
        format.html { render action: 'new' }
        format.json { render json: @question_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /question_categories/1
  # PATCH/PUT /question_categories/1.json
  def update
    respond_to do |format|
      if @question_category.update(question_category_params)
        format.html { redirect_to @question_category, notice: 'Question category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @question_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /question_categories/1
  # DELETE /question_categories/1.json
  def destroy
    @question_category.destroy
    respond_to do |format|
      format.html { redirect_to question_categories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question_category
      @question_category = QuestionCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_category_params
      params.require(:question_category).permit(:question_id, :category_id)
    end
end

app/helpers/question_categories_helper.rb
module QuestionCategoriesHelper
end

app/views/question_categories/_form.html.erb
<%= form_for @question_category, html: {class: "pure-form pure-form-stacked"} do |f| %>
    <fieldset>

      <% if @question_category.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@question_category.errors.count, "error") %> prohibited this question_category from being saved:</h2>

            <ul>
              <% @question_category.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div class="pure-control-group">
        <%= f.label :question_id %><br>
        <%= f.text_field :question_id %>
      </div>

      <div class="pure-control-group">
        <%= f.label :category_id %><br>
        <%= f.text_field :category_id %>
      </div>

      <div class="pure-control-group">
        <div class="pure-controls">
          <%= f.submit class: "pure-button pure-button-primary" %>
        </div>
      </div>

    </fieldset>
<% end %>

app/views/question_categories/edit.html.erb
<h1>Editing question_category</h1>

<%= render 'form' %>

<%= link_to 'Show', @question_category %> |
<%= link_to 'Back', question_categories_path %>

app/views/question_categories/index.html.erb
<% provide(:title, 'Question Categories') %>

<h1>Listing question_categories</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>Category</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @question_categories.each do |question_category| %>
      <tr>
        <td><%= question_category.question %></td>
        <td><%= question_category.category %></td>
        <td><%= link_to 'Show', question_category %></td>
        <td><%= link_to 'Edit', edit_question_category_path(question_category) %></td>
        <td><%= link_to 'Destroy', question_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question category', new_question_category_path %>

app/views/question_categories/new.html.erb
<h1>New question_category</h1>

<%= render 'form' %>

<%= link_to 'Back', question_categories_path %>

app/views/question_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @question_category.question %>
</p>

<p>
  <strong>Category:</strong>
  <%= @question_category.category %>
</p>

<%= link_to 'Edit', edit_question_category_path(@question_category) %> |
<%= link_to 'Back', question_categories_path %>